name: CI
on:
  push:
    branches:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      # - uses: go-semantic-release/action@v1
      #   with:
      #     allow-initial-development-versions: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup semtag
        run: |
          curl -sL https://raw.githubusercontent.com/nico2sh/semtag/master/semtag > semtag
          chmod +x semtag
          sudo mv semtag /usr/local/bin/
      - name: Create semantic tag
        run: |
          semtag final -s auto -o
          git push origin $(semtag get-current)
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
