name: CI
on:
  push:
    branches:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          allow-initial-development-versions: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
